### PR TITLE
When voiding an entry, add option to use date of original entry for the voiding entry, instead of the current date. #117

### PR DESCRIPTION
**Pull request by tudorelu**
#117

### CODE REVIEW

**Comment by koresar** [comment]
If used in production, the cached balances will be stale for some time. Dangerous. But I'm okay with that.
@Uzlopak ?

**Comment by koresar** [comment]
Prettier need to be applied to the both files.

**Comment by hmvs** [comment]
> If used in production, the cached balances will be stale for some time. Dangerous. But I'm okay with that.
> @Uzlopak ?

It makes sense to point it out as a known issue for this use case in README.

**Comment by tudorelu** [comment]
> If used in production, the cached balances will be stale for some time. Dangerous. But I'm okay with that. 

Re cached balances, I could also clear the balances table if `use_original_date` is set to true. 

Or I could add it as a known issue in the README. Happy to do either.

**Comment by koresar** [comment]
known issue is better IMO.

**Comment by tudorelu** [comment]
Okay, all done 👍 let me know if anything else needs doing before we can merge.

**Review by koresar — APPROVED** [review]

**Comment by koresar** [comment]
Published as medici@7.1.0

**Pull request merged**
