### PR TITLE
Feature/multi book commit

### PR DESCRIPTION
**Pull request by ChyzhykTech**
This PR introduces a new helper function **`commit`** designed to handle the transactional commit of multiple **`entries`** within a MongoDB session. Using the **`mongoTransaction`**  helper, ensures atomicity and data integrity during the commit process.

Expected syntax to use:
```
var entry1 = book1.debit().credit();
var entry2 = book2.debit().credit();
const [j1, j2] = await medici.commit(entry1, entry2);
```

### CODE REVIEW

**Comment by ChyzhykTech** [comment]
Could you please provide your expert opinion, @koresar, regarding the new function and share your thoughts?

I want to note that the new function requires the creation of corresponding unit tests. However, before proceeding, I would still like to receive feedback regarding the changes.

**Review by hmvs — APPROVED** [review]

**Comment by koresar** [comment]
I would avoid involving sessions for the single collection document insertions.

**Comment by ChyzhykTech** [comment]
> I would avoid involving sessions for the single collection document insertions.

Dear @koresar,
Following your suggestion, we won't use a session for a single commit. 
Additionally, I've implemented a check to disallow committing zero entries (`MediciError` is thrown).

Could you please review it again?

Thank you.

**Comment by koresar** [comment]
We need to talk. :)

**Pull request closed without merging**
